cp pki/ca.crt /tmp/masashi.hirabayashi-key/
cp pki/issued/server.crt /tmp/masashi.hirabayashi-key/
cp pki/private/server.key /tmp/masashi.hirabayashi-key/
cp pki/issued/client1.domain.tld.crt /tmp/masashi.hirabayashi-key/
cp pki/private/client1.domain.tld.key /tmp/masashi.hirabayashi-key/
cd /tmp/masashi.hirabayashi-key/
